export const iso27001Requirements: { code: string; title: string; parent?: string }[] = [
  { code: "A.5", title: "Organizational controls" },
  { code: "A.5.1", title: "Policies for information security", parent: "A.5" },
  { code: "A.5.2", title: "Information security roles and responsibilities", parent: "A.5" },
  { code: "A.5.3", title: "Segregation of duties", parent: "A.5" },
  { code: "A.5.4", title: "Management responsibilities", parent: "A.5" },
  { code: "A.5.5", title: "Contact with authorities", parent: "A.5" },
  { code: "A.5.6", title: "Contact with special interest groups", parent: "A.5" },
  { code: "A.5.7", title: "Threat intelligence", parent: "A.5" },
  { code: "A.5.8", title: "Information security in project management", parent: "A.5" },
  { code: "A.5.9", title: "Inventory of information and other associated assets", parent: "A.5" },
  { code: "A.5.10", title: "Acceptable use of information and other associated assets", parent: "A.5" },
  { code: "A.5.11", title: "Return of assets", parent: "A.5" },
  { code: "A.5.12", title: "Classification of information", parent: "A.5" },
  { code: "A.5.13", title: "Labelling of information", parent: "A.5" },
  { code: "A.5.14", title: "Information transfer", parent: "A.5" },
  { code: "A.5.15", title: "Access control", parent: "A.5" },
  { code: "A.5.16", title: "Identity management", parent: "A.5" },
  { code: "A.5.17", title: "Authentication information", parent: "A.5" },
  { code: "A.5.18", title: "Access rights", parent: "A.5" },
  { code: "A.5.19", title: "Information security in supplier relationships", parent: "A.5" },
  { code: "A.5.20", title: "Addressing information security within supplier agreements", parent: "A.5" },
  { code: "A.5.21", title: "Managing information security in the ICT supply chain", parent: "A.5" },
  { code: "A.5.22", title: "Monitoring, review and change management of supplier services", parent: "A.5" },
  { code: "A.5.23", title: "Information security for use of cloud services", parent: "A.5" },
  { code: "A.5.24", title: "Information security incident management planning and preparation", parent: "A.5" },
  { code: "A.5.25", title: "Assessment and decision on information security events", parent: "A.5" },
  { code: "A.5.26", title: "Response to information security incidents", parent: "A.5" },
  { code: "A.5.27", title: "Learning from information security incidents", parent: "A.5" },
  { code: "A.5.28", title: "Collection of evidence", parent: "A.5" },
  { code: "A.5.29", title: "Information security during disruption", parent: "A.5" },
  { code: "A.5.30", title: "ICT readiness for business continuity", parent: "A.5" },
  { code: "A.5.31", title: "Legal, statutory, regulatory and contractual requirements", parent: "A.5" },
  { code: "A.5.32", title: "Intellectual property rights", parent: "A.5" },
  { code: "A.5.33", title: "Protection of records", parent: "A.5" },
  { code: "A.5.34", title: "Privacy and protection of PII", parent: "A.5" },
  { code: "A.5.35", title: "Independent review of information security", parent: "A.5" },
  { code: "A.5.36", title: "Compliance with policies, rules and standards for information security", parent: "A.5" },
  { code: "A.5.37", title: "Documented operating procedures", parent: "A.5" },
  { code: "A.6", title: "People controls" },
  { code: "A.6.1", title: "Screening", parent: "A.6" },
  { code: "A.6.2", title: "Terms and conditions of employment", parent: "A.6" },
  { code: "A.6.3", title: "Information security awareness, education and training", parent: "A.6" },
  { code: "A.6.4", title: "Disciplinary process", parent: "A.6" },
  { code: "A.6.5", title: "Responsibilities after termination or change of employment", parent: "A.6" },
  { code: "A.6.6", title: "Confidentiality or non-disclosure agreements", parent: "A.6" },
  { code: "A.6.7", title: "Remote working", parent: "A.6" },
  { code: "A.6.8", title: "Information security event reporting", parent: "A.6" },
  { code: "A.7", title: "Physical controls" },
  { code: "A.7.1", title: "Physical security perimeters", parent: "A.7" },
  { code: "A.7.2", title: "Physical entry", parent: "A.7" },
  { code: "A.7.3", title: "Securing offices, rooms and facilities", parent: "A.7" },
  { code: "A.7.4", title: "Physical security monitoring", parent: "A.7" },
  { code: "A.7.5", title: "Protecting against physical and environmental threats", parent: "A.7" },
  { code: "A.7.6", title: "Working in secure areas", parent: "A.7" },
  { code: "A.7.7", title: "Clear desk and clear screen", parent: "A.7" },
  { code: "A.7.8", title: "Equipment siting and protection", parent: "A.7" },
  { code: "A.7.9", title: "Security of assets off-premises", parent: "A.7" },
  { code: "A.7.10", title: "Storage media", parent: "A.7" },
  { code: "A.7.11", title: "Supporting utilities", parent: "A.7" },
  { code: "A.7.12", title: "Cabling security", parent: "A.7" },
  { code: "A.7.13", title: "Equipment maintenance", parent: "A.7" },
  { code: "A.7.14", title: "Secure disposal or re-use of equipment", parent: "A.7" },
  { code: "A.8", title: "Technological controls" },
  { code: "A.8.1", title: "User endpoint devices", parent: "A.8" },
  { code: "A.8.2", title: "Privileged access rights", parent: "A.8" },
  { code: "A.8.3", title: "Information access restriction", parent: "A.8" },
  { code: "A.8.4", title: "Access to source code", parent: "A.8" },
  { code: "A.8.5", title: "Secure authentication", parent: "A.8" },
  { code: "A.8.6", title: "Capacity management", parent: "A.8" },
  { code: "A.8.7", title: "Protection against malware", parent: "A.8" },
  { code: "A.8.8", title: "Management of technical vulnerabilities", parent: "A.8" },
  { code: "A.8.9", title: "Configuration management", parent: "A.8" },
  { code: "A.8.10", title: "Information deletion", parent: "A.8" },
  { code: "A.8.11", title: "Data masking", parent: "A.8" },
  { code: "A.8.12", title: "Data leakage prevention", parent: "A.8" },
  { code: "A.8.13", title: "Information backup", parent: "A.8" },
  { code: "A.8.14", title: "Redundancy of information processing facilities", parent: "A.8" },
  { code: "A.8.15", title: "Logging", parent: "A.8" },
  { code: "A.8.16", title: "Monitoring activities", parent: "A.8" },
  { code: "A.8.17", title: "Clock synchronization", parent: "A.8" },
  { code: "A.8.18", title: "Use of privileged utility programs", parent: "A.8" },
  { code: "A.8.19", title: "Installation of software on operational systems", parent: "A.8" },
  { code: "A.8.20", title: "Networks security", parent: "A.8" },
  { code: "A.8.21", title: "Security of network services", parent: "A.8" },
  { code: "A.8.22", title: "Segregation of networks", parent: "A.8" },
  { code: "A.8.23", title: "Web filtering", parent: "A.8" },
  { code: "A.8.24", title: "Use of cryptography", parent: "A.8" },
  { code: "A.8.25", title: "Secure development life cycle", parent: "A.8" },
  { code: "A.8.26", title: "Application security requirements", parent: "A.8" },
  { code: "A.8.27", title: "Secure system architecture and engineering principles", parent: "A.8" },
  { code: "A.8.28", title: "Secure coding", parent: "A.8" },
  { code: "A.8.29", title: "Security testing in development and acceptance", parent: "A.8" },
  { code: "A.8.30", title: "Outsourced development", parent: "A.8" },
  { code: "A.8.31", title: "Separation of development, test and production environments", parent: "A.8" },
  { code: "A.8.32", title: "Change management", parent: "A.8" },
  { code: "A.8.33", title: "Test information", parent: "A.8" },
  { code: "A.8.34", title: "Protection of information systems during audit testing", parent: "A.8" },
];
