export const nistCsfRequirements: { code: string; title: string; parent?: string }[] = [
  { code: "GV", title: "Govern" },
  { code: "GV.OC", title: "Organizational Context", parent: "GV" },
  { code: "GV.OC-01", title: "The organizational mission is understood and informs cybersecurity risk management", parent: "GV.OC" },
  { code: "GV.OC-02", title: "Internal and external stakeholders are understood, and their needs and expectations are understood and considered", parent: "GV.OC" },
  { code: "GV.OC-03", title: "Legal, regulatory, and contractual requirements are understood and managed", parent: "GV.OC" },
  { code: "GV.OC-04", title: "Critical objectives, capabilities, and services that stakeholders depend on are understood and communicated", parent: "GV.OC" },
  { code: "GV.OC-05", title: "Outcomes, capabilities, and services that the organization depends on are understood and communicated", parent: "GV.OC" },
  { code: "GV.RM", title: "Risk Management Strategy", parent: "GV" },
  { code: "GV.RM-01", title: "Risk management objectives are established and agreed to by organizational stakeholders", parent: "GV.RM" },
  { code: "GV.RM-02", title: "Risk appetite and risk tolerance statements are established, communicated, and maintained", parent: "GV.RM" },
  { code: "GV.RM-03", title: "Cybersecurity risk management activities and outcomes are included in enterprise risk management processes", parent: "GV.RM" },
  { code: "GV.RM-04", title: "Strategic direction that describes appropriate risk response options is established and communicated", parent: "GV.RM" },
  { code: "GV.RM-05", title: "Lines of communication across the organization are established for cybersecurity risks", parent: "GV.RM" },
  { code: "GV.RM-06", title: "A standardized method for calculating, documenting, categorizing, and prioritizing cybersecurity risks is established", parent: "GV.RM" },
  { code: "GV.RM-07", title: "Strategic opportunities are characterized and included in organizational cybersecurity risk discussions", parent: "GV.RM" },
  { code: "GV.RR", title: "Roles, Responsibilities, and Authorities", parent: "GV" },
  { code: "GV.RR-01", title: "Organizational leadership is responsible and accountable for cybersecurity risk", parent: "GV.RR" },
  { code: "GV.RR-02", title: "Roles, responsibilities, and authorities are established, communicated, understood, and enforced", parent: "GV.RR" },
  { code: "GV.RR-03", title: "Adequate resources are allocated commensurate with the cybersecurity risk strategy", parent: "GV.RR" },
  { code: "GV.RR-04", title: "Cybersecurity is included in human resources practices", parent: "GV.RR" },
  { code: "GV.PO", title: "Policy", parent: "GV" },
  { code: "GV.PO-01", title: "Policy for managing cybersecurity risks is established based on organizational context, cybersecurity strategy, and priorities", parent: "GV.PO" },
  { code: "GV.PO-02", title: "Policy for managing cybersecurity risks is reviewed, updated, communicated, and enforced", parent: "GV.PO" },
  { code: "GV.SC", title: "Cybersecurity Supply Chain Risk Management", parent: "GV" },
  { code: "GV.SC-01", title: "A cybersecurity supply chain risk management program, strategy, objectives, policies, and processes are established and agreed to", parent: "GV.SC" },
  { code: "GV.SC-02", title: "Cybersecurity roles and responsibilities for suppliers, customers, and partners are established, communicated, and coordinated", parent: "GV.SC" },
  { code: "GV.SC-03", title: "Cybersecurity supply chain risk management is integrated into cybersecurity and enterprise risk management", parent: "GV.SC" },
  { code: "GV.SC-04", title: "Suppliers are known and prioritized by criticality", parent: "GV.SC" },
  { code: "GV.SC-05", title: "Requirements to address cybersecurity risks in supply chains are established, prioritized, and integrated", parent: "GV.SC" },
  { code: "GV.SC-06", title: "Planning and due diligence are performed to reduce risks before entering into formal supplier or other third-party relationships", parent: "GV.SC" },
  { code: "GV.SC-07", title: "The risks posed by a supplier, their products and services, and other third parties are understood, recorded, and prioritized", parent: "GV.SC" },
  { code: "GV.SC-08", title: "Relevant suppliers and other third parties are included in incident planning, response, and recovery activities", parent: "GV.SC" },
  { code: "GV.SC-09", title: "Supply chain security practices are integrated into cybersecurity and enterprise risk management programs", parent: "GV.SC" },
  { code: "GV.SC-10", title: "Cybersecurity supply chain risk management plans include provisions for activities that occur after the conclusion of a partnership", parent: "GV.SC" },
  { code: "ID", title: "Identify" },
  { code: "ID.AM", title: "Asset Management", parent: "ID" },
  { code: "ID.AM-01", title: "Inventories of hardware managed by the organization are maintained", parent: "ID.AM" },
  { code: "ID.AM-02", title: "Inventories of software, services, and systems managed by the organization are maintained", parent: "ID.AM" },
  { code: "ID.AM-03", title: "Representations of the organization's authorized network communication and internal and external network data flows are maintained", parent: "ID.AM" },
  { code: "ID.AM-04", title: "Inventories of services provided by suppliers are maintained", parent: "ID.AM" },
  { code: "ID.AM-05", title: "Assets are prioritized based on classification, criticality, resources, and impact on the mission", parent: "ID.AM" },
  { code: "ID.AM-07", title: "Inventories of data and corresponding metadata for designated data types are maintained", parent: "ID.AM" },
  { code: "ID.AM-08", title: "Systems, hardware, software, services, and data are managed throughout their life cycles", parent: "ID.AM" },
  { code: "ID.RA", title: "Risk Assessment", parent: "ID" },
  { code: "ID.RA-01", title: "Vulnerabilities in assets are identified, validated, and recorded", parent: "ID.RA" },
  { code: "ID.RA-02", title: "Cyber threat intelligence is received from information sharing forums and sources", parent: "ID.RA" },
  { code: "ID.RA-03", title: "Internal and external threats to the organization are identified and recorded", parent: "ID.RA" },
  { code: "ID.RA-04", title: "Potential impacts and likelihoods of threats exploiting vulnerabilities are identified and recorded", parent: "ID.RA" },
  { code: "ID.RA-05", title: "Threats, vulnerabilities, likelihoods, and impacts are used to understand inherent risk and inform risk response prioritization", parent: "ID.RA" },
  { code: "ID.RA-06", title: "Risk responses are chosen, prioritized, planned, tracked, and communicated", parent: "ID.RA" },
  { code: "ID.RA-07", title: "Changes and exceptions are managed, assessed for risk impact, recorded, and tracked", parent: "ID.RA" },
  { code: "ID.RA-08", title: "Processes for receiving, analyzing, and responding to vulnerability disclosures are established", parent: "ID.RA" },
  { code: "ID.RA-09", title: "The authenticity and integrity of hardware and software are assessed prior to acquisition and use", parent: "ID.RA" },
  { code: "ID.RA-10", title: "Critical suppliers are assessed prior to acquisition", parent: "ID.RA" },
  { code: "ID.IM", title: "Improvement", parent: "ID" },
  { code: "ID.IM-01", title: "Improvements are identified from evaluations", parent: "ID.IM" },
  { code: "ID.IM-02", title: "Improvements are identified from security tests and exercises", parent: "ID.IM" },
  { code: "ID.IM-03", title: "Improvements are identified from execution of operational processes, procedures, and activities", parent: "ID.IM" },
  { code: "ID.IM-04", title: "Incident response plans and other cybersecurity plans that affect operations are established, communicated, maintained, and improved", parent: "ID.IM" },
  { code: "PR", title: "Protect" },
  { code: "PR.AA", title: "Identity Management, Authentication, and Access Control", parent: "PR" },
  { code: "PR.AA-01", title: "Identities and credentials for authorized users, services, and hardware are managed", parent: "PR.AA" },
  { code: "PR.AA-02", title: "Identities are proofed and bound to credentials based on the context of interactions", parent: "PR.AA" },
  { code: "PR.AA-03", title: "Users, services, and hardware are authenticated", parent: "PR.AA" },
  { code: "PR.AA-04", title: "Identity assertions are protected, conveyed, and verified", parent: "PR.AA" },
  { code: "PR.AA-05", title: "Access permissions, entitlements, and authorizations are defined, managed, enforced, and reviewed", parent: "PR.AA" },
  { code: "PR.AA-06", title: "Physical access to assets is managed, monitored, and enforced commensurate with risk", parent: "PR.AA" },
  { code: "PR.AT", title: "Awareness and Training", parent: "PR" },
  { code: "PR.AT-01", title: "Personnel are provided with awareness and training so that they possess the knowledge and skills to perform general tasks", parent: "PR.AT" },
  { code: "PR.AT-02", title: "Individuals in specialized roles are provided with awareness and training so that they possess the knowledge and skills to perform relevant tasks", parent: "PR.AT" },
  { code: "PR.DS", title: "Data Security", parent: "PR" },
  { code: "PR.DS-01", title: "The confidentiality, integrity, and availability of data-at-rest are protected", parent: "PR.DS" },
  { code: "PR.DS-02", title: "The confidentiality, integrity, and availability of data-in-transit are protected", parent: "PR.DS" },
  { code: "PR.DS-10", title: "The confidentiality, integrity, and availability of data-in-use are protected", parent: "PR.DS" },
  { code: "PR.DS-11", title: "Backups of data are created, protected, maintained, and tested", parent: "PR.DS" },
  { code: "PR.PS", title: "Platform Security", parent: "PR" },
  { code: "PR.PS-01", title: "The configuration of organizational assets is established and maintained", parent: "PR.PS" },
  { code: "PR.PS-02", title: "Software is maintained, replaced, and removed commensurate with risk", parent: "PR.PS" },
  { code: "PR.PS-03", title: "Hardware is maintained, replaced, and removed commensurate with risk", parent: "PR.PS" },
  { code: "PR.PS-04", title: "Log records are generated and made available for continuous monitoring", parent: "PR.PS" },
  { code: "PR.PS-05", title: "Installation and execution of unauthorized software are prevented", parent: "PR.PS" },
  { code: "PR.PS-06", title: "Secure software development practices are integrated, and their performance is monitored", parent: "PR.PS" },
  { code: "PR.IR", title: "Technology Infrastructure Resilience", parent: "PR" },
  { code: "PR.IR-01", title: "Networks and environments are protected from unauthorized logical access and usage", parent: "PR.IR" },
  { code: "PR.IR-02", title: "The organization's technology assets are protected from environmental threats", parent: "PR.IR" },
  { code: "PR.IR-03", title: "Mechanisms are implemented to achieve resilience requirements in normal and adverse situations", parent: "PR.IR" },
  { code: "PR.IR-04", title: "Adequate resource capacity to ensure availability is maintained", parent: "PR.IR" },
  { code: "DE", title: "Detect" },
  { code: "DE.CM", title: "Continuous Monitoring", parent: "DE" },
  { code: "DE.CM-01", title: "Networks and network services are monitored to find potentially adverse events", parent: "DE.CM" },
  { code: "DE.CM-02", title: "The physical environment is monitored to find potentially adverse events", parent: "DE.CM" },
  { code: "DE.CM-03", title: "Personnel activity and technology usage are monitored to find potentially adverse events", parent: "DE.CM" },
  { code: "DE.CM-06", title: "External service provider activities and services are monitored to find potentially adverse events", parent: "DE.CM" },
  { code: "DE.CM-09", title: "Computing hardware and software, runtime environments, and their data are monitored", parent: "DE.CM" },
  { code: "DE.AE", title: "Adverse Event Analysis", parent: "DE" },
  { code: "DE.AE-02", title: "Potentially adverse events are analyzed to better understand associated activities", parent: "DE.AE" },
  { code: "DE.AE-03", title: "Information is correlated from multiple sources", parent: "DE.AE" },
  { code: "DE.AE-04", title: "The estimated impact and scope of adverse events are understood", parent: "DE.AE" },
  { code: "DE.AE-06", title: "Information on adverse events is provided to authorized staff and tools", parent: "DE.AE" },
  { code: "DE.AE-07", title: "Cyber threat intelligence and other contextual information are integrated into the analysis", parent: "DE.AE" },
  { code: "DE.AE-08", title: "Incidents are declared when adverse events meet the defined incident criteria", parent: "DE.AE" },
  { code: "RS", title: "Respond" },
  { code: "RS.MA", title: "Incident Management", parent: "RS" },
  { code: "RS.MA-01", title: "The incident response plan is executed in coordination with relevant third parties", parent: "RS.MA" },
  { code: "RS.MA-02", title: "Incident reports are triaged and validated", parent: "RS.MA" },
  { code: "RS.MA-03", title: "Incidents are categorized and prioritized", parent: "RS.MA" },
  { code: "RS.MA-04", title: "Incidents are escalated or elevated as needed", parent: "RS.MA" },
  { code: "RS.MA-05", title: "The criteria for initiating incident recovery are applied", parent: "RS.MA" },
  { code: "RS.AN", title: "Incident Analysis", parent: "RS" },
  { code: "RS.AN-03", title: "Analysis is performed to establish what has taken place during an incident", parent: "RS.AN" },
  { code: "RS.AN-06", title: "Actions performed during an investigation are recorded", parent: "RS.AN" },
  { code: "RS.AN-07", title: "Incident data and metadata are collected, and their integrity and provenance are preserved", parent: "RS.AN" },
  { code: "RS.AN-08", title: "An incident's magnitude is estimated and validated", parent: "RS.AN" },
  { code: "RS.CO", title: "Incident Response Reporting and Communication", parent: "RS" },
  { code: "RS.CO-02", title: "Internal and external stakeholders are notified of incidents", parent: "RS.CO" },
  { code: "RS.CO-03", title: "Information is shared with designated internal and external stakeholders", parent: "RS.CO" },
  { code: "RS.MI", title: "Incident Mitigation", parent: "RS" },
  { code: "RS.MI-01", title: "Incidents are contained", parent: "RS.MI" },
  { code: "RS.MI-02", title: "Incidents are eradicated", parent: "RS.MI" },
  { code: "RC", title: "Recover" },
  { code: "RC.RP", title: "Incident Recovery Plan Execution", parent: "RC" },
  { code: "RC.RP-01", title: "The recovery portion of the incident response plan is executed once initiated", parent: "RC.RP" },
  { code: "RC.RP-02", title: "Recovery actions are selected, scoped, and prioritized", parent: "RC.RP" },
  { code: "RC.RP-03", title: "The integrity of backups and other restoration assets is verified before using them for restoration", parent: "RC.RP" },
  { code: "RC.RP-04", title: "Critical mission functions and cybersecurity risk management are considered to establish post-incident operational norms", parent: "RC.RP" },
  { code: "RC.RP-05", title: "The integrity of restored assets is verified, systems and services are restored, and normal operating status is confirmed", parent: "RC.RP" },
  { code: "RC.RP-06", title: "The end of incident recovery is declared based on criteria, and incident-related documentation is completed", parent: "RC.RP" },
  { code: "RC.CO", title: "Incident Recovery Communication", parent: "RC" },
  { code: "RC.CO-03", title: "Recovery activities and progress in restoring operational capabilities are communicated to designated internal and external stakeholders", parent: "RC.CO" },
  { code: "RC.CO-04", title: "Public updates on incident recovery are shared using approved methods and messaging", parent: "RC.CO" },
];
