export const soc2Requirements: { code: string; title: string; parent?: string }[] = [
  { code: "CC1", title: "Control Environment" },
  { code: "CC1.1", title: "COSO Principle 1: Demonstrates commitment to integrity and ethical values", parent: "CC1" },
  { code: "CC1.2", title: "COSO Principle 2: Board exercises oversight responsibility", parent: "CC1" },
  { code: "CC1.3", title: "COSO Principle 3: Establishes structure, authority, and responsibility", parent: "CC1" },
  { code: "CC1.4", title: "COSO Principle 4: Demonstrates commitment to competence", parent: "CC1" },
  { code: "CC1.5", title: "COSO Principle 5: Enforces accountability", parent: "CC1" },
  { code: "CC2", title: "Communication and Information" },
  { code: "CC2.1", title: "COSO Principle 13: Uses relevant, quality information", parent: "CC2" },
  { code: "CC2.2", title: "COSO Principle 14: Communicates internally", parent: "CC2" },
  { code: "CC2.3", title: "COSO Principle 15: Communicates externally", parent: "CC2" },
  { code: "CC3", title: "Risk Assessment" },
  { code: "CC3.1", title: "COSO Principle 6: Specifies suitable objectives", parent: "CC3" },
  { code: "CC3.2", title: "COSO Principle 7: Identifies and analyzes risk", parent: "CC3" },
  { code: "CC3.3", title: "COSO Principle 8: Assesses fraud risk", parent: "CC3" },
  { code: "CC3.4", title: "COSO Principle 9: Identifies and analyzes significant change", parent: "CC3" },
  { code: "CC4", title: "Monitoring Activities" },
  { code: "CC4.1", title: "COSO Principle 16: Selects, develops, and performs ongoing and/or separate evaluations", parent: "CC4" },
  { code: "CC4.2", title: "COSO Principle 17: Evaluates and communicates deficiencies", parent: "CC4" },
  { code: "CC5", title: "Control Activities" },
  { code: "CC5.1", title: "COSO Principle 10: Selects and develops control activities", parent: "CC5" },
  { code: "CC5.2", title: "COSO Principle 11: Selects and develops general controls over technology", parent: "CC5" },
  { code: "CC5.3", title: "COSO Principle 12: Deploys through policies and procedures", parent: "CC5" },
  { code: "CC6", title: "Logical and Physical Access Controls" },
  { code: "CC6.1", title: "Logical access security software, infrastructure, and architectures", parent: "CC6" },
  { code: "CC6.2", title: "Prior to issuing system credentials, registered and authorized", parent: "CC6" },
  { code: "CC6.3", title: "Based on authorization, access to protected information assets", parent: "CC6" },
  { code: "CC6.4", title: "Restrictions on physical access to facilities", parent: "CC6" },
  { code: "CC6.5", title: "Discontinues logical and physical protections over physical assets", parent: "CC6" },
  { code: "CC6.6", title: "Security measures against threats outside system boundaries", parent: "CC6" },
  { code: "CC6.7", title: "Restricts the transmission, movement, and removal of information", parent: "CC6" },
  { code: "CC6.8", title: "Controls against threats from malicious software", parent: "CC6" },
  { code: "CC7", title: "System Operations" },
  { code: "CC7.1", title: "Detection and monitoring procedures for security events", parent: "CC7" },
  { code: "CC7.2", title: "Monitors system components for anomalies", parent: "CC7" },
  { code: "CC7.3", title: "Evaluates security events for incidents", parent: "CC7" },
  { code: "CC7.4", title: "Responds to identified security incidents", parent: "CC7" },
  { code: "CC7.5", title: "Identifies and develops activities to mitigate incidents", parent: "CC7" },
  { code: "CC8", title: "Change Management" },
  { code: "CC8.1", title: "Authorizes, designs, develops, configures, documents, tests, approves changes", parent: "CC8" },
  { code: "CC9", title: "Risk Mitigation" },
  { code: "CC9.1", title: "Identifies and assesses risks to objectives", parent: "CC9" },
  { code: "CC9.2", title: "Assesses and manages risks associated with vendors and partners", parent: "CC9" },
  { code: "A1", title: "Additional Criteria for Availability" },
  { code: "A1.1", title: "Maintains, monitors, and evaluates current processing capacity", parent: "A1" },
  { code: "A1.2", title: "Authorizes, designs, develops environmental protections and recovery infrastructure", parent: "A1" },
  { code: "A1.3", title: "Tests recovery plan procedures", parent: "A1" },
  { code: "C1", title: "Additional Criteria for Confidentiality" },
  { code: "C1.1", title: "Identifies and maintains confidential information", parent: "C1" },
  { code: "C1.2", title: "Disposes of confidential information", parent: "C1" },
  { code: "PI1", title: "Additional Criteria for Processing Integrity" },
  { code: "PI1.1", title: "Obtains or generates, uses, and communicates relevant quality information", parent: "PI1" },
  { code: "PI1.2", title: "Implements policies and procedures for system processing", parent: "PI1" },
  { code: "PI1.3", title: "Implements policies and procedures for inputs", parent: "PI1" },
  { code: "PI1.4", title: "Implements policies and procedures for outputs", parent: "PI1" },
  { code: "PI1.5", title: "Implements policies and procedures to store inputs, items in processing, and outputs", parent: "PI1" },
  { code: "P1", title: "Additional Criteria for Privacy" },
  { code: "P1.1", title: "Notice and communication of objectives", parent: "P1" },
  { code: "P2", title: "Privacy - Choice and Consent" },
  { code: "P2.1", title: "Communicates choices available and obtains consent", parent: "P2" },
  { code: "P3", title: "Privacy - Collection" },
  { code: "P3.1", title: "Collects personal information consistent with objectives", parent: "P3" },
  { code: "P3.2", title: "Collects personal information from third parties for specified purposes", parent: "P3" },
  { code: "P4", title: "Privacy - Use, Retention, and Disposal" },
  { code: "P4.1", title: "Limits use of personal information to purposes stated in notice", parent: "P4" },
  { code: "P4.2", title: "Retains personal information consistent with objectives", parent: "P4" },
  { code: "P4.3", title: "Securely disposes of personal information", parent: "P4" },
  { code: "P5", title: "Privacy - Access" },
  { code: "P5.1", title: "Grants identified and authenticated data subjects access to their personal information", parent: "P5" },
  { code: "P5.2", title: "Corrects, amends, or appends personal information", parent: "P5" },
  { code: "P6", title: "Privacy - Disclosure and Notification" },
  { code: "P6.1", title: "Discloses personal information to third parties with consent", parent: "P6" },
  { code: "P6.2", title: "Creates and disseminates information about privacy incidents", parent: "P6" },
  { code: "P6.3", title: "Provides notice of changes to privacy practices", parent: "P6" },
  { code: "P6.4", title: "Provides information about personal information held", parent: "P6" },
  { code: "P6.5", title: "Obtains privacy commitments from third parties", parent: "P6" },
  { code: "P6.6", title: "Remediation of unauthorized personal information", parent: "P6" },
  { code: "P6.7", title: "Notifies affected individuals, regulators, and others of personal information breaches", parent: "P6" },
  { code: "P7", title: "Privacy - Quality" },
  { code: "P7.1", title: "Collects and maintains accurate, up-to-date, complete, and relevant personal information", parent: "P7" },
  { code: "P8", title: "Privacy - Monitoring and Enforcement" },
  { code: "P8.1", title: "Performs compliance reviews and documents resolution", parent: "P8" },
];
